### ISSUE TITLE
unsupported '-fsanitize=thread' / 'i386-pc-linux-gnu'

### ISSUE THREAD

**Issue by RalfHain** [rsmmr/install-clang#11]
Dear Madam or Sir,

install-clang fails over the missing '-fsanitize=thread'.
As far as I understood, this is exprected for my platform.
I personally could live without '-fsanitize=thread', but unfortunately the build process is stopped.

Do You have a hint in which CMakefileList (or the like) I can deactivate '-fsanitize=thread'? So I could proceed even without it?

(Is 32 bit really that exotic today?)
(By the way; I started on a FAT partition, this seems to be exotic also. I continued with ext2)

See logs below

Regards
Ralf Hain

/media/xubuntu/tr/llvm/src/llvm/build-stage1/projects/compiler-rt/lib/tsan/libcxx_tsan/src/libcxx_tsan-stamp/libcxx_tsan-configure-err.log

[100%] Performing configure step for 'libcxx_tsan'
CMake Error at /media/xubuntu/tr/llvm/src/llvm/build-stage1/projects/compiler-rt/lib/tsan/libcxx_tsan/src/libcxx_tsan-stamp/libcxx_tsan-configure.cmake:16 (message):
Command failed: 1

'/usr/bin/cmake' '-DCMAKE_C_COMPILER=/media/xubuntu/tr/llvm/src/llvm/build-stage1/./bin/clang' '-DCMAKE_CXX_COMPILER=/media/xubuntu/tr/llvm/src/llvm/build-stage1/./bin/clang' '-DCMAKE_C_FLAGS= -fsanitize=thread' '-DCMAKE_CXX_FLAGS= -fsanitize=thread' '-DCMAKE_BUILD_TYPE=Release' '-DCMAKE_INSTALL_PREFIX:PATH=/media/xubuntu/tr/llvm/src/llvm/build-stage1/projects/compiler-rt/lib/tsan/libcxx_tsan' '-GUnix Makefiles' '/media/xubuntu/tr/llvm/src/llvm/projects/libcxx'

See also

/media/xubuntu/tr/llvm/src/llvm/build-stage1/projects/compiler-rt/lib/tsan/libcxx_tsan/src/libcxx_tsan-stamp/libcxx_tsan-configure-*.log

make[2]: **\* [projects/compiler-rt/lib/tsan/libcxx_tsan/src/libcxx_tsan-stamp/libcxx_tsan-configure] Fehler 1
make[1]: **\* [projects/compiler-rt/lib/tsan/CMakeFiles/libcxx_tsan.dir/all] Fehler 2
make[1]: **\* Warte auf noch nicht beendete Prozesse...
Linking CXX executable ../../bin/llvm-readobj
[100%] Built target llvm-readobj
make: **\* [all] Fehler 2
    ===
    === Faild building LLVM/clang at stage 1
    ===
    ------------------------------
CMake Error at /usr/share/cmake-2.8/Modules/CMakeTestCXXCompiler.cmake:54 (message):
The C++ compiler "/media/xubuntu/tr/llvm/src/llvm/build-stage1/./bin/clang"
is not able to compile a simple test program.

It fails with the following output:

Change Dir: /media/xubuntu/tr/llvm/src/llvm/build-stage1/projects/compiler-rt/lib/tsan/libcxx_tsan/src/libcxx_tsan-build/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/make "cmTryCompileExec508344078/fast"

make[3]: Betrete Verzeichnis
'/media/xubuntu/tr/llvm/src/llvm/build-stage1/projects/compiler-rt/lib/tsan/libcxx_tsan/src/libcxx_tsan-build/CMakeFiles/CMakeTmp'

/usr/bin/make -f CMakeFiles/cmTryCompileExec508344078.dir/build.make
CMakeFiles/cmTryCompileExec508344078.dir/build

make[4]: Betrete Verzeichnis
'/media/xubuntu/tr/llvm/src/llvm/build-stage1/projects/compiler-rt/lib/tsan/libcxx_tsan/src/libcxx_tsan-build/CMakeFiles/CMakeTmp'

/usr/bin/cmake -E cmake_progress_report
/media/xubuntu/tr/llvm/src/llvm/build-stage1/projects/compiler-rt/lib/tsan/libcxx_tsan/src/libcxx_tsan-build/CMakeFiles/CMakeTmp/CMakeFiles
1

Building CXX object
CMakeFiles/cmTryCompileExec508344078.dir/testCXXCompiler.cxx.o

/media/xubuntu/tr/llvm/src/llvm/build-stage1/./bin/clang -fsanitize=thread
-o CMakeFiles/cmTryCompileExec508344078.dir/testCXXCompiler.cxx.o -c
/media/xubuntu/tr/llvm/src/llvm/build-stage1/projects/compiler-rt/lib/tsan/libcxx_tsan/src/libcxx_tsan-build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx

clang-3.5: error: unsupported option '-fsanitize=thread' for target
'i386-pc-linux-gnu'

make[4]: Verlasse Verzeichnis
'/media/xubuntu/tr/llvm/src/llvm/build-stage1/projects/compiler-rt/lib/tsan/libcxx_tsan/src/libcxx_tsan-build/CMakeFiles/CMakeTmp'

make[4]: ***
[CMakeFiles/cmTryCompileExec508344078.dir/testCXXCompiler.cxx.o] Fehler 1
make[3]: Verlasse Verzeichnis
'/media/xubuntu/tr/llvm/src/llvm/build-stage1/projects/compiler-rt/lib/tsan/libcxx_tsan/src/libcxx_tsan-build/CMakeFiles/CMakeTmp'

make[3]: **\* [cmTryCompileExec508344078/fast] Fehler 2

CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
CMakeLists.txt:7 (project)

**Comment by RalfHain** [comment]
Hello again,

I've tracked it down a bit more.

command:
$ ./install-clang -j 2 /media/xubuntu/tr/llvm  # ie clang-3.5

check:
$ /media/xubuntu/tr/llvm/src/llvm/build-stage1/./bin/clang --version
Target: i386-pc-linux-gnu #   <--- obviously the wrong target was built


install-clang sets LLVM_TARGETS_TO_BUILD=host, which should work according the
documentation. To be on the safe side, I've also tried to set it fixed
to the value X86. The line:
CMAKE_common="-DBUILD_SHARED_LIBS=on -DLLVM_TARGETS_TO_BUILD=X86"
=> same result.


Excerpts from the .log:

  === Building LLVM/clang, stage 0 ...
  -- Target triple: i686-pc-linux-gnu
  -- Targeting X86
  -- Could NOT find LibXml2 (missing:  LIBXML2_LIBRARIES LIBXML2_INCLUDE_DIR) 
   # I have installed them! # aptitude install libxml libxml2-dev


  === Building LLVM/clang, stage 1 ...
  -- Target triple: i686-pc-linux-gnu
  -- Native target architecture is X86
  -- Targeting X86
  CMake Warning at projects/libcxxabi/CMakeLists.txt:252 (message):
    The libc++abi tests are currently only valid when LIBCXXABI_ENABLE_SHARED
    is on, no check target will be available!
    ...
    [ 15%] Built target RTSanitizerCommon.i386   # <-- first hint, that 386 is generated


(
 I've given -m  a try (for clang 3.6), It didn't succeed:
 $ ./install-clang -m -j 2 /media/xubuntu/tr/llvm
    Determining if the include file malloc/malloc.h exists failed with the following output:
    /media/xubuntu/tr/llvm/src/llvm/build-stage1/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:10: fatal error: 'malloc/malloc.h' file not found
)

Maybe its a known problem in the clang-build-process, but I do not know where to search for it.

**Comment by RalfHain** [comment]
For information:
Ubuntu 14.04, aptitude install clang-3.5 
-> also: Target: i386-pc-linux-gnu
-> also: clang: error: unsupported option '-fsanitize=thread' for target 'i386-pc-linux-gnu'
Conclusion: I cannot do build-stages > 0 on this system.

**Comment by BatmanAoD** [comment]
I have the same issue on Debian 7.8.

**Comment by BatmanAoD** [comment]
Oops, sorry, ignore my comment; this is an LLVM issue, not `install-clang` issue (I am not using `install-clang`).

**Comment by sneakernets** [comment]
This also happens on ARMv7. Very frustrating, indeed.

**Comment by rsmmr** [comment]
I've updated the install-clang script for 6.0. closing old tickets, feel free to reopen if still relevant.
