### ISSUE TITLE
patches are applied twice if cmake / subversion not installed and update flag given

### ISSUE THREAD

**Issue by danevandyck** [rsmmr/install-clang#12]
I tried to build the project without cmake installed. The build failed when cmake was not found. I installed cmake and attempted rebuild with the 'update' / '-u' flag. This failed during patch application, I think because patches had already been applied to the source.

**Comment by rsmmr** [comment]
I've updated the install-clang script for 6.0. Closing old tickets, feel free to reopen if still relevant.
