### ISSUE TITLE
Failed patch application causes install script to fail

### ISSUE THREAD

**Issue by rbclark** [rsmmr/install-clang#15]
I have noticed that when running the install-clang script that when running with the default version (release_35), I am getting a broken build due to the patch https://github.com/rsmmr/install-clang/blob/master/patches/fix-external-project-order.patch. This patch does not apply cleanly to release_35 and actually causes the file to have the failed git merge remnants in it. As soon as I manually fixed it the build was able to continue. This specific patch seems to only apply to release_36. Looking at the code it seems that there isn't any code currently to handle failed patches in the install-clang script. It seems like that would fix this problem from happening again.

As a note this is happening for me on Centos 6.7.

**Comment by rsmmr** [comment]
I've updated the install-clang script for 6.0.
